config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }

  resource :cart, only: [:show, :destroy] do 
    collection do 
      post :add, path: ':id/add'
      get :checkout  # cart#checkout
      # /cart/:id/add
      # POST :add, path: '/add/:id'
      # /cart/add/:id
    end 
  end

  resources :orders, only: [:index, :show, :create] do 
    member do 
      put :cancel  # PUT /orders/2/cancel 
      get :pay 
      post :paid  # /order/:id/paid
    end 
  end 
  
  resources :books, only: [:index, :show] do 
    member do
      post :comment # POST /books/:id/comment, to: 'books#comment'  
    end 
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]

  root 'books#index'

  namespace :admin do 
    root 'books#index'   
    resources :books 
    resources :publishers
    resources :categories
  end

  namespace :api do 
    resources :books, only:[] do 
      member do 
        post :favorite  # api/books/:id/favorite/
      end
    end 
  end
end

app/views/shared/frontend/_menu.html.erb
<aside class="column is-2 is-fullheight menu">
<p class="menu-label">
  Category
</p>
<ul class="menu-list">
  <% categories.each do |category| %>
  <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>
<p class="menu-label">
  Publisher
</p>
<ul class="menu-list">
  <% publishers.each do |publisher|%>
  <li><%= link_to publisher.name, publisher_path(publisher) %></li>
  <% end %>
</ul>
</aside>

app/views/shared/frontend/_nav.html.erb
<nav class="navbar is-success" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
    <i class="fas fa-book"></i>
    <% end %>

    <!-- <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
     <span aria-hidden="true"></span>
     <span aria-hidden="true"></span>
     <span aria-hidden="true"></span>
   </a> -->
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Book List", books_path, class: 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item data-controller='cart'">

        <%= link_to cart_path, class: 'button' do%>
        <i class="fas fa-cart-plus"></i>(<%= current_cart.items.count%>)
        <% end %>

        <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to current_user.email, edit_user_registration_path, class: 'button is-light' %>


          <div class="navbar-dropdown">
              <%= link_to 'My Order', orders_path, class: 'navbar-item' %>
            <hr class="navbar-divider">
            <%= link_to "Logout", destroy_user_session_path, method:'delete', class: 'navbar-item' %>
          </div>
        </div>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: 'button is-primary' %>
          <%= link_to "Login", new_user_session_path, class: 'button is-light' %>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</nav>