config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }

  resource :cart, only: [:show, :destroy] do 
    collection do 
      post :add, path: ':id/add'
      get :checkout  # cart#checkout
      # /cart/:id/add
      # POST :add, path: '/add/:id'
      # /cart/add/:id
    end 
  end

  resources :orders, only: [:index, :show, :create] do 
    member do 
      put :cancel  # PUT /orders/2/cancel 
      get :pay 
      post :paid  # /order/:id/paid
    end 
  end 
  
  resources :books, only: [:index, :show] do 
    member do
      post :comment # POST /books/:id/comment, to: 'books#comment'  
    end 
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]

  root 'books#index'

  namespace :admin do 
    root 'books#index'   
    resources :books 
    resources :publishers
    resources :categories
  end

  namespace :api do 
    resources :books, only:[] do 
      member do 
        post :favorite  # api/books/:id/favorite/
      end
    end 
  end
end

app/views/shared/backend/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
  <%= link_to admin_root_path, class: 'navbar-item' do %>
    <i class="fas fa-book"></i>
  <% end %>

  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
     <span aria-hidden="true"></span>
     <span aria-hidden="true"></span>
     <span aria-hidden="true"></span>
   </a>
</div>

<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <%= link_to "Book List", admin_books_path, class: 'navbar-item' %>   
    <%= link_to "Publisher", admin_publishers_path, class: 'navbar-item' %>    
    <%= link_to "Category", admin_categories_path, class: 'navbar-item' %>      
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: 'button is-light' %>
          <%= link_to "Log Out", destroy_user_session_path, method:'delete', class: 'button is-light' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'button is-primary' %>
          <%= link_to "Log In", new_user_session_path, class: 'button is-light' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</nav>