config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }

  resource :cart, only: [:show, :destroy] do 
    collection do 
      post :add, path: ':id/add'
      get :checkout  # cart#checkout
      # /cart/:id/add
      # POST :add, path: '/add/:id'
      # /cart/add/:id
    end 
  end

  resources :orders, only: [:index, :show, :create] do 
    member do 
      put :cancel  # PUT /orders/2/cancel 
      get :pay 
      post :paid  # /order/:id/paid
    end 
  end 
  
  resources :books, only: [:index, :show] do 
    member do
      post :comment # POST /books/:id/comment, to: 'books#comment'  
    end 
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]

  root 'books#index'

  namespace :admin do 
    root 'books#index'   
    resources :books 
    resources :publishers
    resources :categories
  end

  namespace :api do 
    resources :books, only:[] do 
      member do 
        post :favorite  # api/books/:id/favorite/
      end
    end 
  end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  validates :name, presence: true 

  scope :available, -> { where(online: true) }

  has_many :books
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < Admin::BaseController
  before_action :find_publisher, only: [:show, :edit, :update, :destroy ]

  def index
    @publishers = Publisher.all
  end

  def show
  end

  def new
    @publisher = Publisher.new
  end

  def create
     @publisher = Publisher.new(publisher_params)

     if @publisher.save 
       redirect_to admin_publishers_path, notic: 'Publisher added!'
     else 
       render :new
     end
  end

  def edit
  end

  def update 
    if @publisher.update(publisher_params)
      redirect_to admin_publishers_path, notic: 'Publisher updated!!'
    else 
      render :edit
    end
  end

  def destroy
    @publisher.destroy if @publisher 
    redirect_to admin_publishers_path, notic: 'Publisher DELETED!!'
  end

  private 

  def find_publisher 
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name,
                                      :tel,
                                      :address,
                                      :note,
                                      :online)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  layout 'book'

  def show
    @publishers = Publisher.available
    
    @publisher = Publisher.find(params[:id])
    @books = @publisher.books.page(params[:page])
  end
end

app/views/admin/publishers/_form.html.erb
<div class="container">
  <%= form_for([:admin, publisher]) do |f| %>
  <div class="columns">
    <div class="column is-4">
      <div class="field">
        <%= f.label :name, class:'label' %>
        <div class="control">
          <%= f.text_field :name, class:'input' %>
        </div>
      </div>
    </div>
    <div class="column is-4">
      <div class="field">
        <%= f.label :tel, class:'label'%>
        <div class="control">
          <%= f.telephone_field :tel, class:'input'%>
        </div>
      </div>
    </div>
  </div>

  <div class="columns">
    <div class="column is-2">
      <div class="field">
        <%= f.label :address, 'ZIP code', class:'label'%>
        <div class="control">
          <%= f.text_field :address, class:'input'%>
        </div>
      </div>
    </div>
    <div class="column is-6">
      <div class="field">
        <%= f.label :address, 'Address-1', class:'label'%>
        <div class="control">
          <%= f.text_field :address, class:'input'%>
        </div>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column is-8">
      <div class="field">
        <%= f.label :address, 'Address-2', class:'label'%>
        <div class="control">
          <%= f.text_field :address, class:'input'%>
        </div>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column is-8">
      <%= f.label :note, class:' label'%>
      <%= f.text_area :note, class:'input'%>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <%= f.submit class:'button is-light'%>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/publishers/edit.html.erb
<h1 class="title is-3 has-text-grey-light	">Edit Publisher</h1>

<%= render 'form', publisher: @publisher %>

app/views/admin/publishers/index.html.erb
<%= link_to 'Add Publisher', new_admin_publisher_path, class: 'button is-dark'%>
<hr>
<h1 class="title is-3 has-text-grey-light	">Publisher List</h1>

<table class="table is-hoverable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Function</th>
      <th>Function</th>
    </tr>
  </thead>
  <tbody>
    <% @publishers.each do |publisher|%>
    <tr>
      <td>
        <%= link_to publisher.name, admin_publisher_path(publisher)  %>
      </td>
      <td>
        <%= link_to 'Edit', edit_admin_publisher_path(publisher) %>
      </td>
      <td>
        <%= link_to 'Delete', admin_publisher_path(publisher), method:'delete', data:{confirm:'Sure?'}  %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/publishers/new.html.erb
<h1 class="title is-3 has-text-grey-light	">New Publisher</h1>

<%= render 'form', publisher: @publisher %>

app/views/admin/publishers/show.html.erb
<h1 class="title is-3 has-text-grey-light	">
  <%= @publisher.name %>
</h1>