config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }

  resource :cart, only: [:show, :destroy] do 
    collection do 
      post :add, path: ':id/add'
      get :checkout  # cart#checkout
      # /cart/:id/add
      # POST :add, path: '/add/:id'
      # /cart/add/:id
    end 
  end

  resources :orders, only: [:index, :show, :create] do 
    member do 
      put :cancel  # PUT /orders/2/cancel 
      get :pay 
      post :paid  # /order/:id/paid
    end 
  end 
  
  resources :books, only: [:index, :show] do 
    member do
      post :comment # POST /books/:id/comment, to: 'books#comment'  
    end 
  end

  resources :publishers, only: [:show]
  resources :categories, only: [:show]

  root 'books#index'

  namespace :admin do 
    root 'books#index'   
    resources :books 
    resources :publishers
    resources :categories
  end

  namespace :api do 
    resources :books, only:[] do 
      member do 
        post :favorite  # api/books/:id/favorite/
      end
    end 
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :books
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  layout 'backend'

  def index
    @categories = Category.all
  end

  def show
  end

  def new 
    @category = Category.new
  end 

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path, notice: 'Category create!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: 'Category updated!'
    else 
      render :edit
    end
  end

  def destroy
    @category.destroy if @category
    redirect_to admin_categories_path, notice: 'Category was deleted~~~'
  end


  private 

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    layout 'book'
  
    def show
      @categories = Category.all
      
      @category = Category.find(params[:id])
      @books = @category.books.page(params[:page])
    end  
end

app/views/admin/categories/_form.html.erb
<div class="container">
<% @category.errors.any? %>
<% @category.errors.full_messages.each do |msg| %>
<%= msg %>
<% end %>
  <%= form_for([:admin, @category]) do |f| %>
  <div class="columns">
    <div class="column is-4">
      <div class="field">
        <%= f.label :name, class:'label' %>
        <div class="control">
          <%= f.text_field :name, class:'input' %>
        </div>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <%= f.submit class:'button is-light'%>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<h1 class="title is-3 has-text-grey-light">Edit Category</h1>

<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<%= link_to 'Add Category', new_admin_category_path, class: 'button is-dark' %>
<hr>
<h1 class="title is-3 has-text-grey-light" > Categories </h1>

<table class="table is-hoverable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Function</th>
      <th>Function</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category|%>
    <tr>
      <td>
        <%= link_to category.name, admin_category_path(category)  %>
      </td>
      <td>
        <%= link_to 'Edit', edit_admin_category_path(category) %>
      </td>
      <td>
        <%= link_to 'Delete', admin_category_path(category), method:'delete', data:{confirm:'Sure?'}  %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<h1 class="title is-3 has-text-grey-light">New Category</h1>

<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<h1 class="title is-3 has-text-grey-light	">
  <%= @category.name %>
</h1>